### ISSUE TITLE
More explicit labeling

### ISSUE THREAD

**Issue by noamtamim** [riyadhalnur/issuelabeler#11]
Just because someone mentioned the word "bug" in the description, it doesn't mean the issue should be labeled `bug`. Maybe it's a suggestion or question and the person writes "I don't think it's a bug, but...".
And if someone mentions an ["invalid state"](https://github.com/search?q=invalid+state&type=Issues), the issue should not be labeled `invalid`.

However, using GitHub's new multiple issue templates system, I can make sure that the template for bug reports contains the string `label:bug` in the front matter.

The behavior should be configurable in the yml file. `excludeLabels` still applies, because some labels should only be added manually by team members.

**Comment by noamtamim** [comment]
I just want to add that I really like this tool and I'm looking forward to using it. In fact, I think this should be a GitHub feature.

**Comment by riyadhalnur** [comment]
Latest version v2.2.0 can now accept custom overrides -
```yml
custom:
  - location: title
    keywords:
      - 'hi'
    labels:
      - hey
      - h
  - location: body
    keywords:
      - 'hey'
    labels:
      - feature:new
      - hey
  - location: body
    keywords:
      - 'hi'
    labels:
      - h
 ```
