### ISSUE TITLE
Possibility to specify keyword and label explicitly

### ISSUE THREAD

**Issue by php-coder** [riyadhalnur/issuelabeler#13]
Hi, thank you for your bot! It looks very handy but unfortunately I can't start using it as it lacks one feature that I need:

As a user I would like to be able to specify keywords and appropriate labels in the configuration file. In other words, I don't need the magick of recognition but I'd like to use my own static rules.

For example:
- "unit tests" in the title of the issue should be mapped into "area/unit tests" label
- "rename" or "extract" words in the issue title should be mapped to "refactoring" label

Also I'd like to specify where to look for these keywords because mentioning "rename" or "extract" in the issue's body doesn't mean that it's about refactoring. But if these keywords are in the title, then it's definitely an issue about refectoring.

Thanks!

**Comment by dgibbs64** [comment]
This feature would be perfect for my Project.
For example, if the word "Ubuntu" is mentioned then the label "Distro: ubuntu" should be applied. It would save me so much time with labeling issues if this feature is implemented.

**Comment by riyadhalnur** [comment]
Latest version v2.2.0 can now accept custom overrides - 
```yml
custom:
  - location: title
    keywords:
      - 'hi'
    labels:
      - hey
      - h
  - location: body
    keywords:
      - 'hey'
    labels:
      - feature:new
      - hey
  - location: body
    keywords:
      - 'hi'
    labels:
      - h
```
