### ISSUE TITLE
Allow more than one keywords as the yaml is pretending with keyword"s"

### ISSUE THREAD

**Issue by thomasmerz** [riyadhalnur/issuelabeler#38]
**Is your feature request related to a problem? Please describe.**
I would like to **summarize many keywords** to label them with the same label(s).
Without this feature I have to make many entries with location+keyword+labels 😞 

**Describe the solution you'd like**
For example it should be possible to define something like that:
```
   - location: title
     keywords:
       - 'pi-hole'
       - 'pihole'
     labels:
      - pi-hole
      - adblocking
```
You can imagine that this description will got very long for many keywords and hard to maintain… 🤷🏻‍♂️ 

**Describe alternatives you've considered**
Alternatives right now are:
```
   - location: title
     keywords:
       - 'pi-hole'
     labels:
      - pi-hole
      - adblocking
   - location: title
     keywords:
       - 'pihole'
     labels:
      - pi-hole
      - adblocking
```

**Additional context**
There's no any other context or screenshots about the feature request here.
