### ISSUE TITLE
Allow regular expressions as keywords

### ISSUE THREAD

**Issue by thomasmerz** [riyadhalnur/issuelabeler#39]
**Is your feature request related to a problem? Please describe.**
This is related to #38 
I'm always frustrated when I have to define many keywords that I could also define with a regex.

**Describe the solution you'd like**
For example it should be possible to define something like that:
```
   - location: title
     keywords:
       - 'pi?hole.*adblock*'
     labels:
      - pi-hole
      - adblocking
```

**Describe alternatives you've considered**
Alternatives right now are defining many keywords:
```
   - location: title
     keywords:
       - 'pi-hole'
     labels:
      - pi-hole
      - adblocking
   - location: title
     keywords:
       - 'pihole'
     labels:
      - pi-hole
      - adblocking
```

**Additional context**
There's no any other context or screenshots about the feature request here.
