### ISSUE TITLE
unable to add a tag with spaces

### ISSUE THREAD

**Issue by Omzig** [riyadhalnur/issuelabeler#65]
**Describe the bug**
Unable to get a label to work when it has spaces and a - in it.

**To Reproduce**
```
  - location: body
    keywords:
      - 'Critcal'
    labels:
      - 'P1 - critical'
```

**Expected behavior**
a rule with a tag with spaces does not seem to work at all

**Screenshots**
bot does not do anything

**Desktop (please complete the following information):**
chrome
